### ISSUE TITLE
The version of this on the vaadin add-ones site is really old....

### ISSUE THREAD

**Issue by Infiniverse** [Haulmont/vaadin-overlays#6]
... and doesn't reflect the fact that this works on 7.x.

Any chance that you could post an update? (You might get more users if you do).

Cheers,
Joe

**Comment by jreznot** [comment]
Hi,

I cannot update Vaadin Add-on directory since I am not an original author of this addon.

Also I recommend using CssLayout and CSS "position: absolute" for floating content instead of this addon because the addon does not support scrolling of a page content and have a lot of bugs.

This repository is only suitable for legacy projects that used this addon. You can find the latest build on github releases page: https://github.com/Haulmont/vaadin-overlays/releases

**Comment by Infiniverse** [comment]
Ah, CssLayout - many thanks. :)
